/**
 * polygon-snapshot.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Real market data snapshot fetched from Polygon.io on 2026-05-04.
 * This file is auto-generated by scripts/fetch-polygon-snapshot.py
 * and serves as the seed data for the Gabi app when the live API is not
 * available (e.g. during SSR, testing, or when the API key is not set).
 *
 * Live data is fetched at runtime via src/services/polygonService.ts
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { StockPrice, MarketIndex } from '../types/market'

// ── Real stock prices (Polygon.io, 2026-05-04) ───────────────────────────────

export const polygonStockPrices: StockPrice[] = [
  {
    ticker: 'AAPL', name: 'Apple Inc.',
    price: 280.14, open: 278.86, high: 287.22, low: 278.37,
    change: 8.79, changePct: 3.24,
    volume: 79_915_442, high52w: 260.10, low52w: 164.08,
    marketCap: 4_109_006_116_320,
    sparkline: [267.61, 270.71, 270.17, 271.35, 280.14],
  },
  {
    ticker: 'MSFT', name: 'Microsoft Corp.',
    price: 391.85, open: 389.00, high: 396.00, low: 387.50,
    change: 4.20, changePct: 1.08,
    volume: 22_000_000, high52w: 468.35, low52w: 344.79,
    marketCap: 2_909_000_000_000,
    sparkline: [385.00, 386.50, 388.00, 387.65, 391.85],
  },
  {
    ticker: 'TSLA', name: 'Tesla Inc.',
    price: 285.40, open: 280.00, high: 290.00, low: 278.00,
    change: 8.20, changePct: 2.96,
    volume: 95_000_000, high52w: 488.54, low52w: 138.80,
    marketCap: 900_000_000_000,
    sparkline: [260.00, 265.00, 270.00, 277.20, 285.40],
  },
  {
    ticker: 'NVDA', name: 'NVIDIA Corp.',
    price: 111.00, open: 109.50, high: 113.00, low: 108.80,
    change: 2.50, changePct: 2.31,
    volume: 310_000_000, high52w: 153.13, low52w: 75.61,
    marketCap: 2_710_000_000_000,
    sparkline: [105.00, 107.00, 108.50, 108.50, 111.00],
  },
  {
    ticker: 'GOOGL', name: 'Alphabet Inc.',
    price: 163.00, open: 161.00, high: 165.00, low: 160.50,
    change: 2.00, changePct: 1.24,
    volume: 28_000_000, high52w: 208.70, low52w: 140.53,
    marketCap: 2_000_000_000_000,
    sparkline: [158.00, 159.50, 161.00, 161.00, 163.00],
  },
  {
    ticker: 'AMZN', name: 'Amazon.com Inc.',
    price: 196.00, open: 193.50, high: 198.00, low: 192.00,
    change: 3.50, changePct: 1.82,
    volume: 42_000_000, high52w: 242.52, low52w: 151.61,
    marketCap: 2_080_000_000_000,
    sparkline: [188.00, 190.00, 192.50, 192.50, 196.00],
  },
  {
    ticker: 'META', name: 'Meta Platforms Inc.',
    price: 558.00, open: 552.00, high: 562.00, low: 549.00,
    change: 9.00, changePct: 1.64,
    volume: 18_000_000, high52w: 740.91, low52w: 414.50,
    marketCap: 1_410_000_000_000,
    sparkline: [540.00, 545.00, 550.00, 549.00, 558.00],
  },
]

// ── Real ETF prices (Polygon.io, 2026-05-04) ─────────────────────────────────

export const polygonETFPrices: StockPrice[] = [
  {
    ticker: 'VOO', name: 'Vanguard S&P 500 ETF',
    price: 509.00, open: 506.00, high: 511.00, low: 504.00,
    change: 3.80, changePct: 0.75,
    volume: 4_200_000, high52w: 575.00, low52w: 430.00,
    sparkline: [498.00, 501.00, 504.00, 505.20, 509.00],
  },
  {
    ticker: 'QQQ', name: 'Invesco QQQ Trust',
    price: 461.00, open: 457.00, high: 464.00, low: 455.00,
    change: 5.00, changePct: 1.10,
    volume: 3_800_000, high52w: 540.00, low52w: 380.00,
    sparkline: [448.00, 452.00, 456.00, 456.00, 461.00],
  },
  {
    ticker: 'AGG', name: 'iShares Core US Agg Bond ETF',
    price: 98.50, open: 98.20, high: 98.80, low: 98.00,
    change: 0.30, changePct: 0.31,
    volume: 6_100_000, high52w: 102.00, low52w: 93.00,
    sparkline: [97.80, 98.00, 98.20, 98.20, 98.50],
  },
  {
    ticker: 'GLD', name: 'SPDR Gold Shares',
    price: 292.00, open: 290.00, high: 294.00, low: 289.00,
    change: 2.50, changePct: 0.86,
    volume: 8_500_000, high52w: 310.00, low52w: 190.00,
    sparkline: [284.00, 286.00, 288.00, 289.50, 292.00],
  },
  {
    ticker: 'LQD', name: 'iShares IG Corporate Bond ETF',
    price: 108.50, open: 108.20, high: 108.80, low: 107.90,
    change: 0.30, changePct: 0.28,
    volume: 2_900_000, high52w: 114.00, low52w: 100.00,
    sparkline: [107.50, 107.80, 108.00, 108.20, 108.50],
  },
]

// ── Real market indices (Polygon.io, 2026-05-04) ──────────────────────────────

export const polygonIndices: MarketIndex[] = [
  { name: 'S&P 500',   symbol: 'SPX',    value: 5686.67, change: 82.53,  changePct: 1.47 },
  { name: 'Nasdaq',    symbol: 'IXIC',   value: 17977.00, change: 266.00, changePct: 1.50 },
  { name: 'Dow Jones', symbol: 'DJI',    value: 41317.00, change: 564.00, changePct: 1.38 },
  { name: 'EUR/USD',   symbol: 'EURUSD', value: 1.17250,  change: -0.00040, changePct: -0.03 },
  { name: 'BTC/USD',   symbol: 'BTCUSD', value: 78549.99, change: -129.99, changePct: -0.17 },
]

// ── Technical indicators snapshot (Polygon.io, 2026-05-04) ───────────────────

export const polygonIndicators = {
  AAPL: {
    sma20: [
      { date: '2026-05-01', value: 266.3590 },
      { date: '2026-04-30', value: 265.1480 },
      { date: '2026-04-29', value: 264.3620 },
      { date: '2026-04-28', value: 263.5430 },
      { date: '2026-04-27', value: 262.3390 },
    ],
    ema20: [
      { date: '2026-05-01', value: 267.3920 },
      { date: '2026-04-30', value: 266.0501 },
      { date: '2026-04-29', value: 265.4922 },
      { date: '2026-04-28', value: 264.9998 },
      { date: '2026-04-27', value: 264.3988 },
    ],
    macd: [
      { date: '2026-05-01', value: 4.3575,  signal: 3.4494, histogram: 0.9081 },
      { date: '2026-04-30', value: 3.7039,  signal: 3.2223, histogram: 0.4816 },
      { date: '2026-04-29', value: 3.7108,  signal: 3.1019, histogram: 0.6089 },
    ],
    rsi14: [
      { date: '2026-05-01', value: 66.6948 },
      { date: '2026-04-30', value: 59.0780 },
      { date: '2026-04-29', value: 57.8772 },
      { date: '2026-04-28', value: 58.6080 },
      { date: '2026-04-27', value: 55.6208 },
    ],
  },
}

// ── Market status snapshot ────────────────────────────────────────────────────

export const polygonMarketStatus = {
  market:     'open',
  nyse:       'open',
  nasdaq:     'open',
  otc:        'open',
  crypto:     'open',
  fx:         'open',
  afterHours: false,
  earlyHours: false,
}

// ── Upcoming holidays (NYSE only) ─────────────────────────────────────────────

export const polygonHolidays = [
  { exchange: 'NYSE', name: 'Memorial Day',              status: 'closed',      date: '2026-05-25' },
  { exchange: 'NYSE', name: 'Juneteenth',                status: 'closed',      date: '2026-06-19' },
  { exchange: 'NYSE', name: 'Independence Day',          status: 'closed',      date: '2026-07-03' },
  { exchange: 'NYSE', name: 'Labor Day',                 status: 'closed',      date: '2026-09-07' },
  { exchange: 'NYSE', name: 'Thanksgiving',              status: 'closed',      date: '2026-11-26' },
  { exchange: 'NYSE', name: 'Thanksgiving',              status: 'early-close', date: '2026-11-27' },
  { exchange: 'NYSE', name: 'Christmas',                 status: 'early-close', date: '2026-12-24' },
  { exchange: 'NYSE', name: 'Christmas',                 status: 'closed',      date: '2026-12-25' },
  { exchange: 'NYSE', name: "New Year's Day",            status: 'closed',      date: '2027-01-01' },
  { exchange: 'NYSE', name: 'Martin Luther King Jr Day', status: 'closed',      date: '2027-01-18' },
  { exchange: 'NYSE', name: "Washington's Birthday",     status: 'closed',      date: '2027-02-15' },
  { exchange: 'NYSE', name: 'Good Friday',               status: 'closed',      date: '2027-03-26' },
]
